server:
  port: 3344

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://host1:6001/eureka

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xslhjw/springcloud-config.git          #GitHub上面的git仓库名字
          ####搜索目录gitee 仓库名字
          search-paths:
            - springcloud-config
#          username: xslhjw
#          password: Lunsuxiao8#
      ####读取分支
      label: master
##   http://localhost:3344/master/config-test.yml   本地访问即可访问gitee 内容

##引入 rabbitmq
  rabbitmq:
    host: 192.168.81.226
    port: 5673
    username: admin
    password: admin
    virtual-host: my_vhost

###rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'



