server:
  port: 9527
## 使用配置文件需要把前置过滤器关掉
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
#      routes:
#        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#
#        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          #uri: http://localhost:8001          #匹配后提供服务的路由地址
#          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            #- After=2020-05-13T21:55:10.016+08:00[Asia/Shanghai]
#            #- Cookie=username,milo
#            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host1:6001/eureka

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001        #匹配后提供服务的路由地址,转发后的真实地址,
#          uri: lb://provider-order-eureka #匹配后提供服务的路由地址  lb:// 代表从注册中心获取服务
          predicates:
            - Path=/aaa/bbb/payment/get/**     # 断言，路径相匹配的进行路由
#            - Path: /payment/lb
#            - After=2020-05-13T21:55:10.016+08:00[Asia/Shanghai]  #
#            - Cookie=username,xiao               #断言 加上cookie
              #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
          filters:
            # 校验
            # 去除一个前缀
            - StripPrefix=2               #作用去除上面 /aaa/ 访问，相当于 http://127.0.0.1:9527/aaa/payment/get/1 去掉/aaa/  不加的话这个uri 不能访问
            - AddRequestHeader=X-Request-Foo, Bar      #请求前增加请求头
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001          #匹配后提供服务的路由地址，！！！这里uri 加不加/payment/lb 都可以匹配
#          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
#            #- After=2020-05-13T21:55:10.016+08:00[Asia/Shanghai]
#            #- Cookie=username,milo
#            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
