server:
  port: 2003

spring:
  application:
    name: seata-storage-service
  cloud:
#    alibaba:
#      seata:
#        #自定义事务组名称需要与seata-server中的对应
#        tx-service-group: my_tx_group
    nacos:
      discovery:
        server-addr: 192.168.81.63:8848
        group: SEATA_GROUP
        namespace: seata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.81.63:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

seata:
  enabled: true
  application-id: seataAddr
  enable-auto-data-source-proxy: true
  tx-service-group: my_tx_group
  registry:
    type: nacos
    nacos:
      application: seataAddr
      server-addr: 192.168.81.63:8848
      group: SEATA_GROUP
      namespace: seata
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.81.63:8848
      group: SEATA_GROUP
      namespace: seata
      username: nacos
      password: nacos

  service:
    vgroup-mapping:
      my_tx_group: xiao
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false



feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml