server:
  port: 7001
spring:
  application:
    name: consumer-alibaba7001
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.81.226:8848

##设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000

feign:
  client:
    config:
      default: #这里就是指的所有被加载的默认FeignClient实现的服务配置都生效
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    com.xiao.huang.service.PaymentService: debug

